// This file was auto-generated by ML.NET Model Builder. 

using SignalAheadModel_ConsoleApp;
using System.Drawing;
// Create single instance of sample data from first line of dataset for model input
var image = (Bitmap)Image.FromFile(@"C:\Users\TomaszCekało\Pictures\SignalAhead\images.jpg");
SignalAheadModel.ModelInput sampleData = new SignalAheadModel.ModelInput()
{
    ImageSource = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = SignalAheadModel.Predict(sampleData);
Console.WriteLine("\n\nPredicted Boxes:\n");
Console.WriteLine(predictionResult);

