// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class SignalAheadModel
{
    /// <summary>
    /// model input class for SignalAheadModel.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"Label")]
        public string Label { get; set; }

        [ColumnName(@"ImageSource")]
        [Microsoft.ML.Transforms.Image.ImageType(800, 600)]
        public System.Drawing.Bitmap ImageSource { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for SignalAheadModel.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Label")]
        public string Label { get; set; }

        [ColumnName(@"ImageSource")]
        [Microsoft.ML.Transforms.Image.ImageType(800, 600)]
        public System.Drawing.Bitmap ImageSource { get; set; }

        [ColumnName(@"input")]
        public float[] Input { get; set; }

        [ColumnName(@"boxes")]
        public float[] Boxes { get; set; }

        [ColumnName(@"labels")]
        public long[] Labels { get; set; }

        [ColumnName(@"scores")]
        public float[] Scores { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("SignalAheadModel.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
